import "./globals.css";
import { AppWrapper } from "../components/AppWrapper";
import Navbar from "../components/navbar/Navbar"


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       >
        <Navbar/>
        {children}
        {/* <AppWrapper>
        </AppWrapper> */}
      </body>
    </html>
  );
}
