import { NextAuthProvider } from "@/auth-provider/NextAuthProvider";
import { ToastContainer } from "react-toastify";
import { Appwrapper } from "@/components/dashboard/provider/Appwrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <NextAuthProvider>
        <Appwrapper>{children}</Appwrapper>
      </NextAuthProvider>
      <ToastContainer />
    </>
  );
}
